### ISSUE TITLE
Module parse failed: Unexpected token v in JSON at position 1 while parsing near '

### ISSUE THREAD

**Issue by enkechan** [willchb/translate-loader#4]
Hi, thanks for provided this lib!

But I have met this error in webpack5, is this lib compatible with wepack5？

error message: Module parse failed: Unexpected token v in JSON at position 1 while parsing near '

**Comment by willchb** [comment]
@EnkeChan, yes it does work with webpack 5. Try setting type: 'javascript/auto' to config in webpack.config.js.

```js
{
  loader: 'translate-loader',
  type: 'javascript/auto',
}
```

See https://webpack.js.org/configuration/module/#ruletype

**Comment by enkechan** [comment]
It worked! Thanks!
